ConstructionStore/WebStore/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using BusinessLogic.Services;
using DataAccess.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Shared.DTO;
using WebStore.Models;

namespace WebStore.Controllers
{
    [Route("/Basket")]
    public class BasketController : Controller
    {
        private ProductService _productService = new ProductService();
        private BasketDto _basketDto = new BasketDto();

        private void InitializeBasket()
        {
            if (!HttpContext.Session.Keys.Contains("Basket"))
            {
                BasketDto basketDto = new BasketDto();
                string json = JsonSerializer.Serialize<BasketDto>(basketDto);
                HttpContext.Session.SetString("Basket", json);
            }
        }


        [HttpGet]
        [Route("")]
        public async Task<IActionResult> Basket()
        {
            InitializeBasket();

            int? id = HttpContext.Session.GetInt32("UserId");
            _basketDto = JsonSerializer.Deserialize<BasketDto>(HttpContext.Session.GetString("Basket"));
            BasketResponseDto basketResponseDto = new BasketResponseDto();

            basketResponseDto.basketResponseDto = await _productService.GetProductsByListId(_basketDto.Products);
                
            UserModel userModel = new UserModel();
            userModel.ID = id;
            userModel.BasketResponsetDto = basketResponseDto;
            return View(userModel);
        }


        [HttpGet]
        [Route("/AddProductInBasket")]
        public void Add(int idProduct)
        {
            InitializeBasket();
            _basketDto = JsonSerializer.Deserialize<BasketDto>(HttpContext.Session.GetString("Basket"));
            if (_basketDto.Products.ContainsKey(idProduct))
            {                
                _basketDto.Products[idProduct] = _basketDto.Products[idProduct]+1;
            }
            else
            {
                _basketDto.Products.Add(idProduct, 1);                
            }
            string json = JsonSerializer.Serialize(_basketDto);
            HttpContext.Session.SetString("Basket", json);
        }

        [HttpPost]
        [Route("/CountProduct/{id}")]
        public void Counter([FromBody] BasketProductDto basketProductDto,[FromRoute] int id)
        {
            _basketDto = JsonSerializer.Deserialize<BasketDto>(HttpContext.Session.GetString("Basket"));
            _basketDto.Products[id] = basketProductDto.Count;
            string json = JsonSerializer.Serialize(_basketDto);
            HttpContext.Session.SetString("Basket", json);
        }

        [HttpPost]
        [Route("/RemoveProduct/{id}")]
        public void Remover(int id)
        {
            _basketDto = JsonSerializer.Deserialize<BasketDto>(HttpContext.Session.GetString("Basket"));
            _basketDto.Products.Remove(id);
            string json = JsonSerializer.Serialize(_basketDto);
            HttpContext.Session.SetString("Basket", json);
        }
    }
}

ConstructionStore/WebStore/Controllers/CatalogController.cs
using BusinessLogic.Services;
using DataAccess.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Shared.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Models;

namespace WebStore.Controllers
{
    
    [Route("/Catalog")]
    public class CatalogController : Controller
    {
        UserService _userService = new UserService();
        private ProductService _productService = new ProductService();
        private UserModel _userModel = new UserModel();
        [HttpGet]
        [Route("")]
        public async Task<IActionResult> Catalog()
        {
            int? id = HttpContext.Session.GetInt32("UserId");
            _userModel.ID = id;
            UserTypeEnum type = await _userService.GetUserType(id);
            if (type == UserTypeEnum.Admin)
            {
                _userModel.Type = 1;
            }
            else
                _userModel.Type = 0;
            return View(_userModel);
        }

        [HttpGet]
        [Route("/CatalogCategories")]
        public async Task<List<CatalogDto>> ViewCatalog()
        {
            return await _productService.GetCategoryList();
        }

        [HttpGet]
        [Route("/CatalogProducts")]
        public async Task<List<CatalogDto>> ViewProduct(int id)
        {
            return await _productService.GetProductList(id);
        }

        [HttpGet]
        [Route("/CatalogProductsFilter")]
        public async Task<List<CharacteristicDto>> ViewProductFilter(int id)
        {
            return await _productService.GetCharacteristicListDto(id);
        }

        [HttpPost]
        [Route("/FiltrationProduct")]
        public async Task<List<CatalogDto>> FiltrationProduct([FromBody] List<FilterDto> filterDto)
        {
            return await _productService.GetProductFilter(filterDto); ;
        }

        [HttpGet]
        [Route("/Product/{id}")]
        public async Task<CatalogDto> GetProduct([FromRoute] int id)
        {
            return await _productService.GetProduct(id);
        }

        [HttpGet]
        [Route("/ViewProduct/{id}")]
        public IActionResult ViewProductInfo([FromRoute] int id)
        {
            int? idUser = HttpContext.Session.GetInt32("UserId");
            _userModel.ID = idUser;
            _userModel.IdProduct = id;
            return View("../Shared/Product", _userModel);
        }
    }
}

ConstructionStore/WebStore/Controllers/LoginController.cs
using BusinessLogic.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Shared.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using WebStore.Models;

namespace WebStore.Controllers
{
    [Route("/Login")]
    public class LoginController : Controller
    {
        private UserService _user = new UserService();
        public IActionResult Register()
        {
            return Redirect("/Registration");
        }
        [HttpGet]
        [Route("")]
        public IActionResult Login()
        {
            return View("Login");
        }

        [HttpPost]
        public async Task<IActionResult> Login(string login, string password)
        {
            LoginDto loginDto = new LoginDto
            {
                Login = login,
                Password = password
            };
            int? id = await _user.LoginUser(loginDto);
            if (!loginDto.Error)
            {
                HttpContext.Session.SetInt32("UserId", id.Value);
                if (!HttpContext.Session.Keys.Contains("Basket"))
                {
                    BasketDto basketDto = new BasketDto();
                    string json = JsonSerializer.Serialize<BasketDto>(basketDto);
                    HttpContext.Session.SetString("Basket", json);                   
                }
                return Redirect("/");
            }
            UserModel userModel = new UserModel();
            userModel.LoginDto = loginDto;
            return View(userModel);
        }
    }
}

ConstructionStore/WebStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class OrderController : Controller
    {
        [Route("/Order")]
        [HttpGet]
        public IActionResult Order()
        {
            
            int? id = HttpContext.Session.GetInt32("UserId");
            UserModel userModel = new UserModel();
            userModel.ID = id;
            if (id.HasValue)
            {                
                return View(userModel);
            }
            else
            {
                return Redirect("/Registration");
            }
        }
    }
}

ConstructionStore/WebStore/Controllers/ProductController.cs
using BusinessLogic.Services;
using DataAccess.Entity;
using Microsoft.AspNetCore.Mvc;
using Shared.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Models;

namespace WebStore.Controllers
{
    [Route("/AddProduct")]
    public class ProductController : Controller
    {
        private ProductService _productService = new ProductService();
        private UserModel _userModel = new UserModel();
        private ProductDto _productDto = new ProductDto();
        [HttpGet]
        [Route("")]
        public IActionResult AddProduct()
        {
            return View();
        }
        [HttpGet]
        [Route("/ViewAddProduct")]
        public IActionResult ViewAddProduct()
        {
            _productDto.ViewAddProduct = true;
            _userModel.ProductDto= _productDto;
            return View("AddProduct", _userModel);
        }
        [HttpGet]
        [Route("/ViewAddCategory")]
        public IActionResult ViewAddCategory()
        {
            _productDto.ViewAddCategory = true;
            _userModel.ProductDto = _productDto;
            return View("AddProduct", _userModel);
        }
        [HttpGet]
        [Route("/ViewAddCharacteristic")]
        public IActionResult ViewAddCharacteristic()
        {
            _productDto.ViewAddCharacteristic = true;
            _userModel.ProductDto = _productDto;
            return View("AddProduct", _userModel);
        }
        [HttpPost]
        [Route("/ViewAddCharacteristic")]
        public async Task<IActionResult> AddCharacteristic(int type, string name, string unit)
        {
            CharacteristicDto characteristicDto = new CharacteristicDto
            {
                Type = type,
                Name = name,
                Unit = unit
            };
            await _productService.AddCharacteristic(characteristicDto);
            return Redirect("/AddProduct");
        }
        [HttpPost]
        [Route("/ViewAddCategory")]
        public async Task<IActionResult> AddCategory(string name, string[] nameCharacteristic)
        {
            CategoryCharacteristicDto categoryCharacteristicDto = new CategoryCharacteristicDto
            {
                NameCategory = name,
                NameCharacteristic = nameCharacteristic
            };
            if (!await _productService.AddCategory(categoryCharacteristicDto))
            {
                _productDto.ViewAddCategory = true;
                _productDto.ErrorCharacteristic = true;
                _userModel.ProductDto = _productDto;
                return View("AddProduct", _userModel);
            }
            return Redirect("/AddProduct");
        }
        [HttpGet]
        [Route("/ViewCharacteristic")]
        public async Task<List<CharacteristicDto>> AddCharacteristicProduct ([FromQuery] string category) 
        {
            return await _productService.GetCharacteristicListDto(category);            
        }
        [HttpPost]
        [Route("/ViewAddProduct")]
        public async Task<IActionResult> AddProduct(string name, float price, string description, int availability, string category, string[] characterictics)
        {            
            _productDto.Name = name;
            _productDto.Price = price;
            _productDto.Description = description;
            _productDto.Availability = availability;
            _productDto.NameCategory = category;
            _productDto.Characteristics = characterictics;
            await _productService.AddProduct(_productDto);
            return Redirect("/AddProduct");
        }
    }
}

ConstructionStore/WebStore/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogic.Services;
using DataAccess.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Shared.DTO;
using WebStore.Models;

namespace WebStore.Controllers
{
    [Route("/Profile")]
    public class ProfileController : Controller
    {
        private UserService _user = new UserService();
        

        [HttpGet]
        [Route("")]
        public async Task<IActionResult> Profiler()
        {
            int? id = HttpContext.Session.GetInt32("UserId");
            if (id.HasValue)
            {
                User user = await _user.ProfileUser(id);
                ProfileDto profileDto = new ProfileDto
                {
                    Name = user.Name,
                    Surname = user.SurName,
                    Patronimic = user.MiddleName,
                    Email = user.Mail,
                    Phone = user.Telephone,
                    Flag = false
                };
                UserModel userModel = new UserModel();
                userModel.ID = id;
                userModel.ProfileDto = profileDto;
                return View(userModel);
            }
            return Redirect("/Registration");
        }

        [HttpPost]
        [Route("/LogOut")]
        public void ProfileExit()
        {
            HttpContext.Session.Clear();
        }

        [HttpDelete]
        [Route("")]
        public IActionResult ProfileDelete()
        {
            //Implementation
            int? id = HttpContext.Session.GetInt32("UserId");
            Task<bool> Ok = _user.DeleteProfileUser(id);
            HttpContext.Session.Clear();
            return Redirect("/");
        }

        [HttpGet]
        [Route("/ChangeProfile")]
        public async Task<IActionResult> ProfilerChange()
        {
            int? id = HttpContext.Session.GetInt32("UserId");
            User user = await _user.ProfileUser(id);
            ProfileDto profileDto = new ProfileDto
            {
                Name = user.Name,
                Surname = user.SurName,
                Patronimic = user.MiddleName,
                Email = user.Mail,
                Phone = user.Telephone,
                OldPassword = user.Password,
                Flag = true
            };
            UserModel userModel = new UserModel();
            userModel.ID = id;
            userModel.ProfileDto = profileDto;
            return View("/Views/Shared/Profiler.cshtml", userModel);
        }

        [HttpPost]
        [Route("/ChangeProfile")]
        public async Task<IActionResult> ProfilerSave(string name, string surName, string patronimic, string telephone, string email, string oldPassword, string newPassword)
        {
            UserModel userModel = new UserModel();
            ProfileDto profile = new ProfileDto
            {
                Name = name,
                Surname = surName,
                Patronimic = patronimic,
                Email = email,
                Phone = telephone,
                OldPassword = oldPassword,
                NewPassword = newPassword,
                Flag = true
            };
            int? id = HttpContext.Session.GetInt32("UserId");
            userModel.ID = id;
            User user = await _user.ProfileUser(id);
            await _user.ChangeProfileUser(user, profile);
            if (!profile.ErrorEmail && !profile.ErrorTel && !profile.ErrorPassword)
            {
                profile.Flag = false;
            }

            userModel.ProfileDto = profile;
            return View("/Views/Shared/Profiler.cshtml", userModel);         
        }
    }
}

ConstructionStore/WebStore/Controllers/RegistrationController.cs
using BusinessLogic.Services;
using DataAccess.Entity;
using DataAccess.Methods;
using Microsoft.AspNetCore.Mvc;
using Shared.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore.Models;

namespace WebStore.Controllers
{
    [Route("/Registration")]
    public class RegistrationController : Controller
    {
        private UserService _user = new UserService();

        public IActionResult Login()
        {
            return Redirect("/Login");
        }
        [HttpGet]
        [Route("")]
        public IActionResult Register()
        {
            return View("Register");
        }

        [HttpPost]
        public async Task<IActionResult> Register(string surName, string name, string middleName, string telephone, string email, string password, string login)
        {
            RegistrationDto registration = new RegistrationDto
            {
                Name = name,
                SurName = surName,
                MiddleName = middleName,
                Mail = email,
                Login = login,
                Telephone = telephone,
                Password = password
            };
            await _user.RegisterUser(registration);
            if (!registration.ErrorEmail && !registration.ErrorLogin && !registration.ErrorTel)
            {
                return Redirect("/");
            }
            UserModel userModel = new UserModel();
            userModel.RegistrationDto = registration;
            return View(userModel);
        }
    }
}

ConstructionStore/WebStore/Views/Shared/AddProduct.cshtml
@model WebStore.Models.UserModel
@{ Layout = Layout; }

<!DOCTYPE>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/login.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script>
        var i = 0;
        function AddCharacteristic() {
            $("#ViewCharacteristic").append(`<div class="mb-3">
                                                <input type="text" class="form-control" name="nameCharacteristic[` + i + `]" id="nameCharacteristic[` + i + `]" placeholder="Название характеристики">
                                            </div>`);
            i++;
        }
    </script>
    <script>
        function ViewCharacteristic() { 
            $.ajax({
                url: '/ViewCharacteristic',
                method: 'get',             
                dataType: 'json',
                contentType: 'application/json',
                data: { category: $('#category').val()  },
                success: function (data) {
                    let length = data.length;                    
                    if (length == 0) {
                        document.getElementById("error").style.display = 'block';

                    } else {
                        document.getElementById("error").style.display = 'none';
                        for (let i = 0; i < length; i++) {
                            let type = data[i].type;
                            if (type == 1) {
                                $("#ViewCharacteristic").append(`<div class="mb-3">
                                                                    <input type="number" class="form-control" placeholder="`+ data[i].name + `" name="characterictics[` + i + `]">
                                                                </div>`);
                            } else if (type == 2) {
                                $("#ViewCharacteristic").append(`<div class="mb-3">
                                                                    <input type="text" class="form-control" placeholder="`+ data[i].name + `"name="characterictics[` + i + `]">
                                                                </div>`);
                            } else $("#ViewCharacteristic").append(`<div class="mb-3">
                                                                      <label class="form-check-label" for="flexCheckDefault">`+ data[i].name + `:</label>
                                                                      <select class="form-select form-select-sm" aria-label=".form-select-sm example" name="characterictics[` + i + `]">
                                                                        <option selected>Есть/Нет</option>
                                                                        <option value="1">Есть</option>
                                                                        <option value="2">Нет</option>
                                                                      </select>
                                                                    </div>`);
                        }
                    }                        
                }
            });
        }        
    </script>
</head>
<body>
    @if (Model == null)
    {
    <div class="d-grid gap-3 d-md-block">
        @Html.ActionLink("Добавление товара", "ViewAddProduct", null, null, new { @class = "btn btn-primary" })
        @Html.ActionLink("Добавление категории", "ViewAddCategory", null, null, new { @class = "btn btn-primary" })
        @Html.ActionLink("Добавление характеристики", "ViewAddCharacteristic", null, null, new { @class = "btn btn-primary" })
    </div>
    }
    else
    {
        if(Model.ProductDto.ViewAddProduct)
        {
            <form class="login-box">                
                <div class="mb-3">
                    <input type="text" class="form-control" name="name" placeholder="Наименование">
                </div>
                <div class="mb-3">
                    <input type="number" class="form-control" name="price" placeholder="Цена">
                </div>
                <div class="mb-3">
                    <textarea class="form-control" placeholder="Описание" name="description" style="height: 100px"></textarea>
                </div>
                <div class="mb-3">
                    <input type="text" class="form-control" name="availability" placeholder="Сколько штук в наличии">
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Категория" aria-describedby="button-addon2" id="category" name="category">
                    <button class="btn btn-outline-secondary" onclick="ViewCharacteristic(); return false;">Характеристики</button>
                </div>
                <div id="error" style="display:none">
                    <div class="alert alert-danger d-flex align-items-center" role="alert">
                        <div>
                            Характеристики либо не существует, либо у нее не давлены характеристики!
                        </div>
                    </div>
                </div>                
                <div class="mb-3" id="ViewCharacteristic">

                </div>
                <div class="mb-3">
                    <button asp-controller="Product" formmethod="post" type="submit" class="btn btn-primary">Добавить</button>
                </div> 
            </form>
        }
        if (Model.ProductDto.ViewAddCategory)
        {
            <form class="login-box"> 
                @if (Model.ProductDto.ErrorCharacteristic)
                 {
                    <div class="alert alert-danger d-flex align-items-center" role="alert">
                    @*<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill" /></svg>*@
                        <div>
                            Ошибка! Одной или несколько характеристик не существуют!
                        </div>
                    </div>
                 }
                <div class="mb-3">
                    <input type="text" class="form-control" name="name" placeholder="Название категории">
                </div>
                <div class="mb-3" id="ViewCharacteristic">

                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" onclick="AddCharacteristic(); return false;">Добавить характеристику</button>
                </div>
                <div class="mb-3">
                    <button asp-controller="Product" formmethod="post" type="submit" class="btn btn-primary">Добавить</button>
                </div>                
            </form>
        }
        if (Model.ProductDto.ViewAddCharacteristic)
        {
            <form class="login-box">
                <div class="col-md-4">
                    <div class="mb-3">
                        <select class="form-select form-select-sm" aria-label=".form-select-sm example" name="type">
                            <option selected>Тип характеристики</option>
                            <option value="1">Числовой</option>
                            <option value="2">Строковый</option>
                            <option value="3">Есть/Нет</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <input type="text" class="form-control" name="name" placeholder="Название">
                    </div>
                    <div class="mb-3">
                        <input type="text" class="form-control" name="unit" placeholder="Единица имерения">
                    </div>
                    <div class="mb-3">
                        <button asp-controller="Product" formmethod="post" type="submit" class="btn btn-primary">Добавить</button>
                    </div>
                </div>
            </form>
        }
    }
</body>
</html>

ConstructionStore/WebStore/Views/Shared/Basket.cshtml
@model WebStore.Models.UserModel
@{ Layout = Layout; }

<!DOCTYPE>
<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/login.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script>
        function countProduct(id) {
            var count = $("#" + id).val();
            if (count > 0) {
                $.ajax({
                    url: '/CountProduct/' + id,
                    method: 'POST',
                    dataType: 'json',
                    contentType: 'application/json',
                    data: JSON.stringify({ count: count }),
                    success: function (data) {

                    }
                });
            }
            else if (count==0)
            {
                $.ajax({
                    url: '/RemoveProduct/' + id,
                    method: 'POST',
                    dataType: 'json',
                    contentType: 'application/json',
                });
                
                alert("Товар успешно удалён из корзины.")
            }
            else {
                
                alert("Невозможно применить значение меньшее 0 к количеству товаров.");
            }
            window.location.reload();
        }

        function costCalculation()
        {
            document.getElementById('dataKeeper')
        }
    </script>
</head>
<body>
    <h2>Корзина товаров</h2>
    <hr>
    <div class="text-center" p-2>
        <table class="table table-bordered table-striped table-sm">
            <thead>
                <tr>
                    <th>Внешний вид</th>
                    <th>Название</th>
                    <th>Стоимость</th>
                    <th>Количество</th>
                </tr>
            </thead>
            @foreach (var item in Model.BasketResponsetDto.basketResponseDto)
            {
                <tr>
                    @{
                        string Path = "/imgProduct/" + @item.Key.Id + ".jpg";
                    }
                    <td><img src="@Path" alt="Изображение не найдено" onerror="this.src=`/imgProduct/default.png`" width=100 height=100></td>
                    <td>@item.Key.Name</td>
                    <td>@item.Key.Price</td>
                    <td>
                        <input id="@item.Key.Id" type="number" onchange="countProduct(@item.Key.Id); return false;"
                               min="0" max="100" value="@item.Value">
                    </td>
                </tr>
            }
        </table>
    </div>


    <div class="container">
        <div class="row mb-3">
            <div class="col-3">Общий чек: @Model.BasketResponsetDto.costCalculation() руб.</div>
            <div class="col-8"></div>
            @if (Model.BasketResponsetDto.basketResponseDto.Count > 0)
            {
                <div class="col-1"><a href="/Order">Заказать</a></div>
            }
        </div>
    </div>
</body>
</html>

ConstructionStore/WebStore/Views/Shared/Index.cshtml
@{
    Layout = Layout;
}

<!DOCTYPE>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/index.css" />
    <title>Главная</title>
</head>
<body>   
    <div class="container">
            <figure class="text-center">
                <blockquote class="blockquote">
                    <p class="h1"><b>Почему выбирают нас</b></p>
                </blockquote>
            </figure>
        <div class="row">
            <div class="col-4">
                <img src="/kaska.jpg" class="rounded mx-auto d-block">
                <p class="h6 text-center">У нас только самые качественные товары. Работаем с множеством популярных брендов. Кажды товар на складе проверяется на брак цпециалистом.</p>
            </div>
            <div class="col-4"></div>
            <div class="col-4">
                <img src="/price.png" class="rounded mx-auto d-block">
                <p class="h6 text-center">У нас самые низкие цены, множество акций и распродаж.</p>
            </div>
        </div>
        <div class="row align-content-center">
            <img src="/logo_main.png" class="rounded mx-auto d-block">
        </div>
        <div class="row">
            <div class="col-4">
                <img src="/dostavka.jpg" class="rounded mx-auto d-block">
                <p class="h6 text-center">Мы предоставляем бесплтную доставку товаров по все России. Вы можете быть уверены, что товар придет в целости и сохранности.</p>
            </div>
            <div class="col-4"></div>
            <div class="col-4">
                <img src="/service.png" class="rounded mx-auto d-block">
                <p class="h6 text-center">Мы учитываем ваши пожелания и рады любым отзывам, потому что для нас важно становиться лучше.</p>
            </div>
        </div>
    </div>
</body>
</html>